/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimesRouteImport } from './routes/times'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CarteirinhaRouteImport } from './routes/carteirinha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesTeamIdRouteImport } from './routes/times.$teamId'
import { Route as MercadoEditarRouteImport } from './routes/mercado.editar'
import { Route as MercadoUserIdRouteImport } from './routes/mercado.$userId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApoioTeamIdRouteImport } from './routes/apoio.$teamId'
import { Route as AdminTimesRouteImport } from './routes/admin.times'
import { Route as AdminTimeRouteImport } from './routes/admin.time'
import { Route as AdminParceirosRouteImport } from './routes/admin.parceiros'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp/webhook'

const TimesRoute = TimesRouteImport.update({
  id: '/times',
  path: '/times',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirinhaRoute = CarteirinhaRouteImport.update({
  id: '/carteirinha',
  path: '/carteirinha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesTeamIdRoute = TimesTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TimesRoute,
} as any)
const MercadoEditarRoute = MercadoEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoUserIdRoute = MercadoUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MercadoRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioTeamIdRoute = ApoioTeamIdRouteImport.update({
  id: '/apoio/$teamId',
  path: '/apoio/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimesRoute = AdminTimesRouteImport.update({
  id: '/times',
  path: '/times',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimeRoute = AdminTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/qrcode': typeof QrcodeRoute
  '/ranking': typeof RankingRoute
  '/times': typeof TimesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/time': typeof AdminTimeRoute
  '/admin/times': typeof AdminTimesRoute
  '/apoio/$teamId': typeof ApoioTeamIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/mercado/$userId': typeof MercadoUserIdRoute
  '/mercado/editar': typeof MercadoEditarRoute
  '/times/$teamId': typeof TimesTeamIdRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/qrcode': typeof QrcodeRoute
  '/ranking': typeof RankingRoute
  '/times': typeof TimesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/time': typeof AdminTimeRoute
  '/admin/times': typeof AdminTimesRoute
  '/apoio/$teamId': typeof ApoioTeamIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/mercado/$userId': typeof MercadoUserIdRoute
  '/mercado/editar': typeof MercadoEditarRoute
  '/times/$teamId': typeof TimesTeamIdRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/qrcode': typeof QrcodeRoute
  '/ranking': typeof RankingRoute
  '/times': typeof TimesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/time': typeof AdminTimeRoute
  '/admin/times': typeof AdminTimesRoute
  '/apoio/$teamId': typeof ApoioTeamIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/mercado/$userId': typeof MercadoUserIdRoute
  '/mercado/editar': typeof MercadoEditarRoute
  '/times/$teamId': typeof TimesTeamIdRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/carteirinha'
    | '/home'
    | '/login'
    | '/mercado'
    | '/parceiros'
    | '/qrcode'
    | '/ranking'
    | '/times'
    | '/admin/financeiro'
    | '/admin/parceiros'
    | '/admin/time'
    | '/admin/times'
    | '/apoio/$teamId'
    | '/checkout/return'
    | '/mercado/$userId'
    | '/mercado/editar'
    | '/times/$teamId'
    | '/api/public/mp/webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/carteirinha'
    | '/home'
    | '/login'
    | '/mercado'
    | '/parceiros'
    | '/qrcode'
    | '/ranking'
    | '/times'
    | '/admin/financeiro'
    | '/admin/parceiros'
    | '/admin/time'
    | '/admin/times'
    | '/apoio/$teamId'
    | '/checkout/return'
    | '/mercado/$userId'
    | '/mercado/editar'
    | '/times/$teamId'
    | '/api/public/mp/webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/carteirinha'
    | '/home'
    | '/login'
    | '/mercado'
    | '/parceiros'
    | '/qrcode'
    | '/ranking'
    | '/times'
    | '/admin/financeiro'
    | '/admin/parceiros'
    | '/admin/time'
    | '/admin/times'
    | '/apoio/$teamId'
    | '/checkout/return'
    | '/mercado/$userId'
    | '/mercado/editar'
    | '/times/$teamId'
    | '/api/public/mp/webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CarteirinhaRoute: typeof CarteirinhaRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRouteWithChildren
  ParceirosRoute: typeof ParceirosRoute
  QrcodeRoute: typeof QrcodeRoute
  RankingRoute: typeof RankingRoute
  TimesRoute: typeof TimesRouteWithChildren
  ApoioTeamIdRoute: typeof ApoioTeamIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/times': {
      id: '/times'
      path: '/times'
      fullPath: '/times'
      preLoaderRoute: typeof TimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteirinha': {
      id: '/carteirinha'
      path: '/carteirinha'
      fullPath: '/carteirinha'
      preLoaderRoute: typeof CarteirinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/$teamId': {
      id: '/times/$teamId'
      path: '/$teamId'
      fullPath: '/times/$teamId'
      preLoaderRoute: typeof TimesTeamIdRouteImport
      parentRoute: typeof TimesRoute
    }
    '/mercado/editar': {
      id: '/mercado/editar'
      path: '/editar'
      fullPath: '/mercado/editar'
      preLoaderRoute: typeof MercadoEditarRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/$userId': {
      id: '/mercado/$userId'
      path: '/$userId'
      fullPath: '/mercado/$userId'
      preLoaderRoute: typeof MercadoUserIdRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio/$teamId': {
      id: '/apoio/$teamId'
      path: '/apoio/$teamId'
      fullPath: '/apoio/$teamId'
      preLoaderRoute: typeof ApoioTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/times': {
      id: '/admin/times'
      path: '/times'
      fullPath: '/admin/times'
      preLoaderRoute: typeof AdminTimesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/time': {
      id: '/admin/time'
      path: '/time'
      fullPath: '/admin/time'
      preLoaderRoute: typeof AdminTimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminTimeRoute: typeof AdminTimeRoute
  AdminTimesRoute: typeof AdminTimesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminTimeRoute: AdminTimeRoute,
  AdminTimesRoute: AdminTimesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MercadoRouteChildren {
  MercadoUserIdRoute: typeof MercadoUserIdRoute
  MercadoEditarRoute: typeof MercadoEditarRoute
}

const MercadoRouteChildren: MercadoRouteChildren = {
  MercadoUserIdRoute: MercadoUserIdRoute,
  MercadoEditarRoute: MercadoEditarRoute,
}

const MercadoRouteWithChildren =
  MercadoRoute._addFileChildren(MercadoRouteChildren)

interface TimesRouteChildren {
  TimesTeamIdRoute: typeof TimesTeamIdRoute
}

const TimesRouteChildren: TimesRouteChildren = {
  TimesTeamIdRoute: TimesTeamIdRoute,
}

const TimesRouteWithChildren = TimesRoute._addFileChildren(TimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CarteirinhaRoute: CarteirinhaRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRouteWithChildren,
  ParceirosRoute: ParceirosRoute,
  QrcodeRoute: QrcodeRoute,
  RankingRoute: RankingRoute,
  TimesRoute: TimesRouteWithChildren,
  ApoioTeamIdRoute: ApoioTeamIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
